[project]
authors = ["denkiwakame <denkivvakame@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "faiss-gpu-build"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4.0"

[tasks]
configure = { cmd = [
  "cmake",
  "-DFAISS_ENABLE_GPU=ON",
  "-S",
  "faiss",
  "-B",
  "build",
] }
build = { cmd = "make -C build -j16 faiss", depends-on = ["configure"] }
build-python = "make -C build -j swigfaiss"

[dependencies]
python = "3.11.*"
cuda = "12.*"
numpy = ">=2.1.3,<3"
mkl = ">=2025.0.0,<2026"

[build-dependencies]
cmake = ">=3.31.1,<4"
cxx-compiler = ">=1.8.0,<2"
make = ">=4.4.1,<5"
swig = ">=4.3.0,<5"
gflags = ">=2.2.2,<3"
pkg-config = ">=0.29.2,<0.30"


[feature.test.pypi-dependencies]
setuptools = ">=75.6.0,<76"

[feature.test.tasks]
install = "cd build/faiss/python && python setup.py install"
dataset = "wget -qO- ftp://ftp.irisa.fr/local/texmex/corpus/sift.tar.gz | tar xz && mv sift sift1M && rm -f sift.tar.gz"
import = "python -c 'import faiss;print(faiss.get_num_gpus())'"

[environments]
test = ["test"]
